import = ["/Users/wangquanjiang/.config/alacritty/themes/dracula.toml"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Medium" }
size = 15.0

[font.glyph_offset]
x = 0
y = 2

[font.offset]
x = 0
y = 6

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Equals"
mods = "Command"

[window]
dynamic_padding = true
opacity = 1
decorations = "Transparent"

[window.padding]
x = 5
y = 22

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 600
blink_timeout = 0
