import = ["/Users/wangquanjiang/.config/alacritty/themes/dracula.toml"]

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 2

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Equals"
mods = "Command"

[window]
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 10
y = 5
